apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: balu361988/zomato:latest  # this will be replaced by Jenkins
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002

