apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: balu361988/zomato:latest
        ports:
        - containerPort: 9090   # ✅ Corrected port
---
apiVersion: v1
kind: Service
metadata:
  name: zomato
spec:
  type: NodePort
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 9090         # ✅ Forward traffic to 9090 inside the pod
      nodePort: 30002

